const themeToggle=document.getElementById('themeToggle'),body=document.body;
const savedTheme=localStorage.getItem('theme'),sysDark=window.matchMedia('(prefers-color-scheme: dark)').matches;
const isDark=savedTheme==='dark'||(!savedTheme&&sysDark);
function applyTheme(dark){if(dark)body.classList.add('dark-mode');else body.classList.remove('dark-mode');localStorage.setItem('theme',dark?'dark':'light');}
applyTheme(isDark);
async function toggleTheme(){if(!document.startViewTransition){body.classList.toggle('dark-mode');localStorage.setItem('theme',body.classList.contains('dark-mode')?'dark':'light');return;}await document.startViewTransition(()=>{body.classList.toggle('dark-mode');localStorage.setItem('theme',body.classList.contains('dark-mode')?'dark':'light');}).ready;const{top,left,width,height}=themeToggle.getBoundingClientRect();const x=left+width/2,y=top+height/2;const maxRadius=Math.hypot(Math.max(left,innerWidth-left),Math.max(top,innerHeight-top));document.documentElement.animate({clipPath:[`circle(0px at ${x}px ${y}px)`,`circle(${maxRadius}px at ${x}px ${y}px)`]},{duration:1000,easing:'ease-in-out',pseudoElement:'::view-transition-new(root)'});}
themeToggle?.addEventListener('click',toggleTheme);
const menuToggle=document.getElementById('menuToggle'),menuCard=document.getElementById('menuCard'),menuClose=document.getElementById('menuClose'),backdrop=document.getElementById('backdrop');
function openMenu(){menuCard.classList.add('open');backdrop.classList.add('visible');document.body.style.overflow='hidden';if(menuToggle){menuToggle.style.opacity='0';menuToggle.style.visibility='hidden';menuToggle.setAttribute('aria-expanded', 'true');}setTimeout(() => menuClose.focus(), 100);}
function closeMenu(){menuCard.classList.remove('open');backdrop.classList.remove('visible');document.body.style.overflow='';if(menuToggle){menuToggle.style.opacity='1';menuToggle.style.visibility='visible';menuToggle.setAttribute('aria-expanded', 'false');}menuToggle.focus();}
menuToggle?.addEventListener('click',e=>{e.stopPropagation();menuCard.classList.contains('open')?closeMenu():openMenu();});
menuClose?.addEventListener('click',closeMenu);
backdrop?.addEventListener('click',closeMenu);
document.querySelectorAll('.menu-link').forEach(l=>l.addEventListener('click',closeMenu));
document.addEventListener('keydown', (e) => {if (e.key === 'Escape' && menuCard.classList.contains('open')) {closeMenu();menuToggle?.focus();}});
const backToTopBtn=document.getElementById('backToTop');
window.addEventListener('scroll',()=>{themeToggle?.classList.toggle('scrolled',window.scrollY>35);if(backToTopBtn){if(window.scrollY>300)backToTopBtn.classList.add('visible');else backToTopBtn.classList.remove('visible');}},{passive:true});
backToTopBtn?.addEventListener('click',()=>{window.scrollTo({top:0,behavior:'smooth'});});
document.querySelectorAll('.faq-question').forEach(question => {question.addEventListener('click', () => {const item = question.parentElement;const answer = item.querySelector('.faq-answer');const isActive = question.classList.contains('active');document.querySelectorAll('.faq-question').forEach(q => {q.classList.remove('active');q.parentElement.querySelector('.faq-answer').classList.remove('show');});if (!isActive) {question.classList.add('active');answer.classList.add('show');}});});
document.addEventListener('DOMContentLoaded',()=>{const publishTimeEl=document.getElementById("publish-time");if(publishTimeEl){const utcTime=publishTimeEl.getAttribute("data-utc");if(utcTime){const date=new Date(utcTime);const formatted=date.toLocaleString(undefined,{year:"numeric",month:"long",day:"numeric",hour:"numeric",minute:"2-digit",hour12:true});const parts=formatted.split(' at ');if(parts.length===2){publishTimeEl.innerHTML=`<span>${parts[0]} at </span><span>${parts[1]}</span>`;}else{publishTimeEl.innerHTML=`<span>${formatted}</span>`;}}}
const headline=document.getElementById('articleMainTitle');const breadcrumbCurrent=document.querySelector('.breadcrumb li[aria-current="page"]');if(headline&&breadcrumbCurrent){let titleText=headline.textContent.trim();if(titleText.length>30){titleText=titleText.substring(0,30)+'...';}breadcrumbCurrent.textContent=titleText;}
function scrollToAuthor(){const authorSection=document.getElementById('authorSection');if(!authorSection)return;const sectionRect=authorSection.getBoundingClientRect();const targetScroll=window.pageYOffset+sectionRect.top-(window.innerHeight/2)+(authorSection.offsetHeight/2);window.scrollTo({top:targetScroll,behavior:'smooth'});setTimeout(()=>{authorSection.style.transition='box-shadow .5s ease';authorSection.style.boxShadow='0 0 0 3px rgba(14,123,127,.4)';setTimeout(()=>{authorSection.style.boxShadow='';},1500);},400);}
document.getElementById('authorMetaBtn')?.addEventListener('click',scrollToAuthor);
const container=document.getElementById('main-source-container');if(container){const allPills=Array.from(container.querySelectorAll('.src-pill-btn'));const LIMIT=3;if(allPills.length>LIMIT){const hiddenPills=allPills.slice(LIMIT);hiddenPills.forEach(pill=>pill.classList.add('src-hidden'));const toggleBtn=document.createElement('button');toggleBtn.className='src-pill-btn src-dd-toggle';toggleBtn.setAttribute('aria-label','Show more sources');toggleBtn.innerHTML='<span class="toggle-text">More</span><span class="dots-icon">...</span>';container.appendChild(toggleBtn);toggleBtn.addEventListener('click',function(){hiddenPills.forEach((pill,index)=>{pill.classList.remove('src-hidden');pill.classList.add('src-reveal-anim');pill.style.animationDelay=`${index*0.05}s`;});this.classList.add('src-hidden');});}}
const cards=document.querySelectorAll('#editorsPicksContainer .editors-article-card');if(cards.length){const articles=[];cards.forEach(card=>{const title=card.querySelector('.editors-article-title');const link=card.querySelector('.editors-read-btn');if(title&&link){articles.push({title:title.textContent.trim(),href:link.getAttribute('href')});}});if(articles.length){const pick=articles[Math.floor(Math.random()*articles.length)];const box=document.getElementById('relatedArticleBox');const linkEl=document.getElementById('relatedArticleLink');const textEl=document.getElementById('relatedArticleText');if(box&&linkEl&&textEl){textEl.textContent=pick.title;linkEl.setAttribute('href',pick.href);box.style.display='flex';}}}
const copyBtn=document.getElementById('copyLinkBtn');if(copyBtn){copyBtn.addEventListener('click',()=>{navigator.clipboard.writeText(window.location.href).then(()=>{copyBtn.classList.add('copied');setTimeout(()=>{copyBtn.classList.remove('copied');},2000);}).catch(err=>{console.error('Failed to copy: ',err);});});}
const y=document.getElementById('currentYear');if(y)y.textContent=new Date().getFullYear();});
